# creating numpy array

In [2]:
import numpy as np
a=np.array([1,2,3,4,5],float)

In [3]:
a

array([1., 2., 3., 4., 5.])

In [4]:
type(a)

numpy.ndarray

# Other ways to create arrays

In [74]:
np.arange(1,6,2, dtype=int)

array([1, 3, 5])

# creating identity matrix

In [75]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Here, the function array takes two arguments: the list to be converted into the array and the type of each member of the list. Array elements are accessed, sliced, and manipulated just like lists:


In [5]:
a[2]

3.0

In [6]:
a[1:3]

array([2., 3.])

In [7]:
a[:3]

array([1., 2., 3.])

In [8]:
a[2:]

array([3., 4., 5.])

# Arrays can be multidimensional.

In [9]:
multidimension=np.array([[1,2,3],[5,6,7]],int)

In [10]:
multidimension

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
multidimension.shape

(2, 3)

# row vice  access(no idication about column)

In [25]:
multidimension[0]

array([1, 2, 3])

# column vice access(no idication about row)

In [23]:
multidimension[:,0]

array([1, 5])

In [26]:
len(multidimension)

2

# The "in" statement can be used to test if values are present in an array:


In [27]:
10 in multidimension

False

In [28]:
6 in multidimension

True

# reshaping the array(Notice that the reshape function creates a new array and does not itself modify the original array.)

In [29]:
onedimensional=np.array(range(1,11))

In [30]:
onedimensional

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
twodimensional=onedimensional.reshape(2,5)

In [32]:
twodimensional

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
new_Two=onedimensional.reshape(5,2)

In [34]:
new_Two

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
a=np.array([1,2,3,4,5],float)
print(a)
b=a.copy()
print(b)
a[0]=0
print(a)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]
[0. 2. 3. 4. 5.]


# Lists can also be created from arrays:

In [39]:
c=a.tolist()
print(c)

[0.0, 2.0, 3.0, 4.0, 5.0]


In [40]:
d=a.tostring()
print(d)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@'


In [45]:
converted=np.fromstring(d)
print(converted)

[0. 2. 3. 4. 5.]


C:\Users\Sujan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


# One can fill an array with a single value:

In [46]:
converted.fill(0)
print(converted)

[0. 0. 0. 0. 0.]


# transpose of an array

In [53]:
a=np.array([range(1,5),range(6,10)])
print(a)
print(a.transpose())

[[1 2 3 4]
 [6 7 8 9]]
[[1 6]
 [2 7]
 [3 8]
 [4 9]]


In [54]:
multidimension=np.array([[1,2,3],[5,6,7]],int)

In [55]:
multidimension

array([[1, 2, 3],
       [5, 6, 7]])

# to print multidimension into one dimension use flatten

In [56]:
multidimension.flatten()

array([1, 2, 3, 5, 6, 7])

# concatenation

In [62]:
a = np.array([1,2], float)

print(f'dimension of a is {a.shape}')
b = np.array([3,4,5,6], float)
print(f'dimension of b is {b.shape}')
c = np.array([7,8,9], float)
print(f'dimension of a is {c.shape}')

dimension of a is (2,)
dimension of b is (4,)
dimension of a is (3,)


In [58]:
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print('via column\n',np.concatenate((a,b),axis=1))
print('via row\n',np.concatenate((a,b),axis=0))

via column
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
via row
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [77]:
np.eye(4, k=2, dtype=float)


array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Array mathematics

In [81]:
A=np.array(([1,2],[3,4]),float)

In [82]:
A

array([[1., 2.],
       [3., 4.]])

In [83]:
B=np.array(([5,6],[7,8]),float)

In [84]:
B

array([[5., 6.],
       [7., 8.]])

In [90]:
print(A+B)

[[ 6.  8.]
 [10. 12.]]


In [92]:
print(B-A)

[[4. 4.]
 [4. 4.]]


In [93]:
print(B/A)

[[5.         3.        ]
 [2.33333333 2.        ]]


In [94]:
print(A%B)

[[1. 2.]
 [3. 4.]]


In [99]:
print(5%5)

0


In [86]:
C=A.dot(B)

In [87]:
C

array([[19., 22.],
       [43., 50.]])

In [88]:
D=A*B

In [89]:
D

array([[ 5., 12.],
       [21., 32.]])

In [100]:
E=A**B

In [101]:
E

array([[1.0000e+00, 6.4000e+01],
       [2.1870e+03, 6.5536e+04]])

# Numpy functions: abs,sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos,arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh

# Array iteration

In [2]:
import numpy as np
A=np.array(range(1,4))
for x in A:
    print(x)

1
2
3


In [3]:
B=np.array([range(0,3),range(2,5)],float)
for x,y,z in B:
    print(x*y*z)

0.0
24.0


In [4]:
B


array([[0., 1., 2.],
       [2., 3., 4.]])

In [8]:
print(A)
print(A.sum())
print(A.prod())
print(A.mean())
print(A.var())
print(A.std())
print(A.max())
print(A.min())
print(A.argmin())
print(A.argmax())
print(np.isnan(A))
print(np.isfinite(A))

[1 2 3]
6
6
2.0
0.6666666666666666
0.816496580927726
3
1
0
2
[False False False]
[ True  True  True]


In [120]:
print(B)
print(B.max(axis=0))
print(B.max(axis=1))

[[0. 1. 2.]
 [2. 3. 4.]]
[2. 3. 4.]
[2. 4.]


In [124]:
print(B.sort())

None


In [125]:
B

array([[0., 1., 2.],
       [2., 3., 4.]])

In [128]:
c=B.flatten()

In [130]:
c[2]=10

In [131]:
c

array([ 0.,  1., 10.,  2.,  3.,  4.])

In [133]:
print(c.sort())

None


In [139]:
c[1]=2

In [140]:
c

array([ 0.,  2.,  2.,  3.,  4., 10.])

In [144]:
print(np.unique(c))

[ 0.  2.  3.  4. 10.]


In [9]:
import numpy as np
A=np.array([range(1,3),range(5,7)])

In [10]:
A

array([[1, 2],
       [5, 6]])

In [14]:
A[A>=2]

array([2, 5, 6])

In [20]:
#indexing a two dimensional array using another array
C=np.array(([23,45,67],[89,100,200]),float)
D=np.array([0,1,0,1,0,0],int)
E=np.array([0,0,1,0,1,0],int)
C[D,E]

array([23., 89., 45., 89., 45., 23.])

In [21]:
F=C[D]

In [22]:
F

array([[ 23.,  45.,  67.],
       [ 89., 100., 200.],
       [ 23.,  45.,  67.],
       [ 89., 100., 200.],
       [ 23.,  45.,  67.],
       [ 23.,  45.,  67.]])

In [23]:
C=np.array(([23,45,67,89,100,200]),float)
D=np.array([3,1,2,5,4,0],int)
C.take(D)

array([ 89.,  45.,  67., 200., 100.,  23.])

In [29]:
#new matrix is formed with reference to the index in a vertical manner
C=np.array(([23,45,67],[89,100,200]),float)
D=np.array([0,1,2,1,0,2],int)
C.take(D,axis=1)

array([[ 23.,  45.,  67.,  45.,  23.,  67.],
       [ 89., 100., 200., 100.,  89., 200.]])

In [30]:
#new matrix is formed with reference to the index in a horizontal manner(Maximum number of row is 2 so 0 and 1 are the index)
C=np.array(([23,45,67],[89,100,200]),float)
D=np.array([0,1,1,1,0,0],int)
C.take(D,axis=0)

array([[ 23.,  45.,  67.],
       [ 89., 100., 200.],
       [ 89., 100., 200.],
       [ 89., 100., 200.],
       [ 23.,  45.,  67.],
       [ 23.,  45.,  67.]])

In [38]:
import numpy as np
D=np.array([0,1,2,1,0,2],int)
B=np.array([100,200,300,400,500,600],int)
print(D.put([0,4,5],100))

None


In [39]:
D.put([0,4,5],100)

In [40]:
A=np.array([range(1,4),range(4,7),range(10,13)],float)

# Matrix manipulations

In [41]:
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [10., 11., 12.]])

In [43]:
np.linalg.det(A)

2.86437540353291e-15

In [45]:
vals,vecs=np.linalg.eig(A)

In [46]:
vals

array([ 1.93923048e+01, -1.39230485e+00,  8.41239522e-17])

In [47]:
vecs

array([[ 0.19047623,  0.6835874 ,  0.40824829],
       [ 0.42237766,  0.22419772, -0.81649658],
       [ 0.88618052, -0.69458163,  0.40824829]])

In [49]:
B=np.linalg.inv(A)

In [50]:
B

array([[-2.09469750e+15,  3.14204625e+15, -1.04734875e+15],
       [ 4.18939500e+15, -6.28409250e+15,  2.09469750e+15],
       [-2.09469750e+15,  3.14204625e+15, -1.04734875e+15]])

In [52]:
np.dot(A,B)

array([[ 0.75 ,  1.   , -0.125],
       [ 1.5  ,  2.   , -0.25 ],
       [-1.   ,  4.   ,  1.5  ]])

# Singular value decomposition ((analogous to diagonalization of a nonsquare matrix)

In [57]:
A=np.array([range(100,104),range(200,204)],float)

In [58]:
U,s,Vh=np.linalg.svd(A)

In [59]:
U

array([[-0.44988401, -0.89308699],
       [-0.89308699,  0.44988401]])

In [60]:
s

array([451.2505045 ,   0.99105395])

In [61]:
Vh

array([[-0.49552476, -0.49850087, -0.50147698, -0.50445309],
       [ 0.67413293,  0.22692924, -0.22027445, -0.66747815],
       [-0.42303575,  0.30473152,  0.65964421, -0.54133998],
       [-0.34790912,  0.77919106, -0.51465475,  0.08337282]])

# About polynomials

In [63]:
np.poly([1,2,3])

array([ 1., -6., 11., -6.])

In [64]:
np.roots([1,-6,11,-6])

array([3., 2., 1.])

In [65]:
np.polyint([1,1,1,1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [66]:
np.polyder([0.25,0.3333,0.5,1,0])

array([1.    , 0.9999, 1.    , 1.    ])

# The function polyval evaluates a polynomial at a particular point.  Consider 𝑥^3− 2𝑥^2 + 2 evaluated at 𝑥 = 4: 

In [67]:
np.polyval([1, -2, 0, 2], 4)

34

In [68]:
x = [1, 2, 3, 4, 5, 6, 7, 8] 
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2)

array([ 0.375     , -0.88690476,  1.05357143])